FROM node:23.1.0 AS build1
ARG VERSION
ENV APP_VER=production.${VERSION:-v1.0}
RUN mkdir -p /var/node
WORKDIR /var/node
ADD src ./
RUN npm install

FROM node:23.1.0-alpine3.20 AS prod
ARG VERSION
ENV APP_VER=production.${VERSION:-v1.0}
COPY --from=build1 /var/node /var/node
WORKDIR /var/node
EXPOSE 3000
ENTRYPOINT [ "./bin/www" ]
